### PR TITLE
Paginated table

### PR DESCRIPTION
**Pull request by olikjh**
image

image

### CODE REVIEW

**Comment by olikjh** [comment]
@CarolineTerblanche this should be a separate task, as all tags need to be updated at the same time in Spoon. If Anna has done those changes, she can move it to spoon to Tag component

**Comment by AnnaGuzniak** [comment]
Could you please restyle pagination as it is done in invisionapp for spoon-ui Pagination component.
https://projects.invisionapp.com/d/main#/console/18422513/397702725/preview

**Comment by melissapalmer** [comment]
@olikjh I'll create a new task for the styling of tags. 

**However:** please do ensure the pagination numbers are styled correctly here. 
See spoon design work at: https://projects.invisionapp.com/share/EGTTHAI7AWU#/screens/397702725

image

**Comment by melissapalmer** [comment]
> Could you please restyle pagination as it is done in invisionapp for spoon-ui Pagination component.
> https://projects.invisionapp.com/d/main#/console/18422513/397702725/preview

I have created RM https://redmine.bigbaobab.org/issues/3007 to do the pagination styling

**Comment by melissapalmer** [comment]
> A few small changes - the tags need to be styled like the tags in Spoon:
> Screenshot 2020-03-02 at 14 21 01
> 
> The tag styling is here on Invision:
> https://projects.invisionapp.com/share/EGTTHAI7AWU#/screens/397702725
> 
> I know Anna has already styled the table if that can help you?

RM https://redmine.bigbaobab.org/issues/3008 created for styling of the tags.

**Pull request merged**
